# 공통 설정
spring:
  main:
    web-application-type: none
  profiles:
    active: jdbc
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql


file:
  blacklist-path: ${user.home}/data/customer_blacklist.csv

---

# file 프로필 설정
spring:
  config:
    activate:
      on-profile: file

file:
  voucher-path: ${user.home}/prod/data/vouchers.csv



